training_params:
  batch_size: 1024
  epochs: 5
  logging_frequency: 400
  shuffle: true
  device: cuda
  optimizer_parms:
    optimizer_type: AdamW
    optimizer_options:
      lr: 0.005
    use_scheduler: true
model_config:
  model_type: FeedForwardPredictor
  params:
    input_dim: 2
    hidden_dim: 1024
    output_dim: 2
    num_hidden_layers: 8
    hash_embedding_params:
      num_embeddings: 1000000
      embedding_dim: 100
      num_buckets: 10000
      num_hashes: 4